FIPS_CODES_COUNTRY_NAME_MAP = {
    'AC': 'Antigua and Barbuda',
    'AE': 'United Arab Emirates',
    'AF': 'Afghanistan',
    'AG': 'Algeria',
    'AJ': 'Azerbaijan',
    'AL': 'Albania',
    'AM': 'Armenia',
    'AO': 'Angola',
    'AQ': 'American Samoa [United States]',
    'AR': 'Argentina',
    'AS': 'Australia',
    'AU': 'Austria',
    'AY': 'Antarctica',
    'BA': 'Bahrain',
    'BB': 'Barbados',
    'BC': 'Botswana',
    'BD': 'Bermuda [United Kingdom]',
    'BE': 'Belgium',
    'BF': 'Bahamas, The',
    'BG': 'Bangladesh',
    'BH': 'Belize',
    'BK': 'Bosnia and Herzegovina',
    'BL': 'Bolivia',
    'BM': 'Burma',
    'BN': 'Benin',
    'BO': 'Belarus',
    'BP': 'Solomon Islands',
    'BR': 'Brazil',
    'BU': 'Bulgaria',
    'BX': 'Brunei',
    'BY': 'Burundi',
    'CA': 'Canada',
    'CB': 'Cambodia',
    'CD': 'Chad',
    'CE': 'Sri Lanka',
    'CF': 'Congo (Brazzaville)',
    'CG': 'Congo (Kinshasa)',
    'CH': 'China',
    'CI': 'Chile',
    'CJ': 'Cayman Islands [United Kingdom]',
    'CK': 'Cocos (Keeling) Islands [Australia]',
    'CM': 'Cameroon',
    'CO': 'Colombia',
    'CQ': 'Northern Mariana Islands [United States]',
    'CS': 'Costa Rica',
    'CT': 'Central African Republic',
    'CU': 'Cuba',
    'CV': 'Cape Verde',
    'CW': 'Cook Islands [New Zealand]',
    'CY': 'Cyprus',
    'DA': 'Denmark',
    'DO': 'Dominica',
    'DR': 'Dominican Republic',
    'EC': 'Ecuador',
    'EG': 'Egypt',
    'EI': 'Ireland',
    'EK': 'Equatorial Guinea',
    'EN': 'Estonia',
    'ER': 'Eritrea',
    'ES': 'El Salvador',
    'ET': 'Ethiopia',
    'EU': 'Europa Island [France]',
    'EZ': 'Czech Republic',
    'FG': 'French Guiana [France]',
    'FI': 'Finland',
    'FJ': 'Fiji',
    'FK': 'Falkland Islands (Islas Malvinas) [United Kingd',
    'FM': 'Federated States of Micronesia',
    'FP': 'French Polynesia',
    'FR': 'France',
    'FS': 'French Southern and Antarctic Lands [France]',
    'GA': 'Gambia, The',
    'GB': 'Gabon',
    'GG': 'Georgia',
    'GH': 'Ghana',
    'GI': 'Gibraltar [United Kingdom]',
    'GL': 'Greenland [Denmark]',
    'GM': 'Germany',
    'GP': 'Guadeloupe [France]',
    'GQ': 'Guam [United States]',
    'GR': 'Greece',
    'GT': 'Guatemala',
    'GV': 'Guinea',
    'GY': 'Guyana',
    'HO': 'Honduras',
    'HR': 'Croatia',
    'HU': 'Hungary',
    'IC': 'Iceland',
    'ID': 'Indonesia',
    'IN': 'India',
    'IO': 'British Indian Ocean Territory [United Kingdom]',
    'IR': 'Iran',
    'IS': 'Israel',
    'IT': 'Italy',
    'IV': "Cote D'Ivoire",
    'IZ': 'Iraq',
    'JA': 'Japan',
    'JM': 'Jamaica',
    'JN': 'Jan Mayen [Norway]',
    'JO': 'Jordan',
    'JQ': 'Johnston Atoll [United States]',
    'JU': 'Juan De Nova Island [France]',
    'KE': 'Kenya',
    'KG': 'Kyrgyzstan',
    'KN': 'Korea, North',
    'KR': 'Kiribati',
    'KS': 'Korea, South',
    'KT': 'Christmas Island [Australia]',
    'KU': 'Kuwait',
    'KZ': 'Kazakhstan',
    'LA': 'Laos',
    'LE': 'Lebanon',
    'LG': 'Latvia',
    'LH': 'Lithuania',
    'LI': 'Liberia',
    'LO': 'Slovakia',
    'LQ': 'Palmyra Atoll [United States]',
    'LT': 'Lesotho',
    'LU': 'Luxembourg',
    'LY': 'Libya',
    'MA': 'Madagascar',
    'MB': 'Martinique [France]',
    'MC': 'Macau S.A.R',
    'MD': 'Moldova',
    'MF': 'Mayotte [France]',
    'MG': 'Mongolia',
    'MI': 'Malawi',
    'MJ': 'Montenegro',
    'MK': 'Macedonia',
    'ML': 'Mali',
    'MO': 'Morocco',
    'MP': 'Mauritius',
    'MQ': 'Midway Islands [United States}',
    'MR': 'Mauritania',
    'MT': 'Malta',
    'MU': 'Oman',
    'MV': 'Maldives',
    'MX': 'Mexico',
    'MY': 'Malaysia',
    'MZ': 'Mozambique',
    'NC': 'New Caledonia [France]',
    'NE': 'Niue [New Zealand]',
    'NF': 'Norfolk Island [Australia]',
    'NG': 'Niger',
    'NH': 'Vanuatu',
    'NI': 'Nigeria',
    'NL': 'Netherlands',
    'NN': 'Sint Maarten',
    'NO': 'Norway',
    'NP': 'Nepal',
    'NS': 'Suriname',
    'NU': 'Nicaragua',
    'NZ': 'New Zealand',
    'PA': 'Paraguay',
    'PC': 'Pitcairn Islands [United Kingdom]',
    'PE': 'Peru',
    'PK': 'Pakistan',
    'PL': 'Poland',
    'PM': 'Panama',
    'PO': 'Portugal',
    'PP': 'Papua New Guinea',
    'PS': 'Palau',
    'PU': 'Guinea-Bissau',
    'QA': 'Qatar',
    'RE': 'Reunion [France]',
    'RI': 'Serbia',
    'RM': 'Marshall Islands',
    'RO': 'Romania',
    'RP': 'Philippines',
    'RQ': 'Puerto Rico [United States]',
    'RS': 'Russia',
    'RW': 'Rwanda',
    'SA': 'Saudi Arabia',
    'SB': 'Saint Pierre and Miquelon [France]',
    'SE': 'Seychelles',
    'SF': 'South Africa',
    'SG': 'Senegal',
    'SH': 'Saint Helena [United Kingdom]',
    'SI': 'Slovenia',
    'SL': 'Sierra Leone',
    'SN': 'Singapore',
    'SP': 'Spain',
    'ST': 'Saint Lucia',
    'SU': 'Sudan',
    'SV': 'Svalbard [Norway]',
    'SW': 'Sweden',
    'SX': 'South Georgia and the South Sandwich Islands [U',
    'SY': 'Syria',
    'SZ': 'Switzerland',
    'TD': 'Trinidad and Tobago',
    'TE': 'Tromelin Island [France]',
    'TH': 'Thailand',
    'TI': 'Tajikistan',
    'TL': 'Tokelau [New Zealand]',
    'TN': 'Tonga',
    'TO': 'Togo',
    'TS': 'Tunisia',
    'TU': 'Turkey',
    'TV': 'Tuvalu',
    'TX': 'Turkmenistan',
    'TZ': 'Tanzania',
    'UC': 'Curacao',
    'UG': 'Uganda',
    'UK': 'United Kingdom',
    'UP': 'Ukraine',
    'US': 'United States',
    'UV': 'Burkina Faso',
    'UY': 'Uruguay',
    'UZ': 'Uzbekistan',
    'VE': 'Venezuela',
    'VM': 'Vietnam',
    'VQ': 'Virgin Islands [United States]',
    'WA': 'Namibia',
    'WF': 'Wallis and Futuna [France]',
    'WI': 'Western Sahara',
    'WQ': 'Wake Island [United States]',
    'WZ': 'Swaziland',
    'ZA': 'Zambia',
    'ZI': 'Zimbabwe'
}

ISO_CODES_COUNTRY_NAME_MAP = {
    "AF": "Afghanistan",
    "AX": "Aland Islands",
    "AL": "Albania",
    "DZ": "Algeria",
    "AS": "American Samoa",
    "AD": "Andorra",
    "AO": "Angola",
    "AI": "Anguilla",
    "AQ": "Antarctica",
    "AG": "Antigua And Barbuda",
    "AR": "Argentina",
    "AM": "Armenia",
    "AW": "Aruba",
    "AU": "Australia",
    "AT": "Austria",
    "AZ": "Azerbaijan",
    "BS": "Bahamas",
    "BH": "Bahrain",
    "BD": "Bangladesh",
    "BB": "Barbados",
    "BY": "Belarus",
    "BE": "Belgium",
    "BZ": "Belize",
    "BJ": "Benin",
    "BM": "Bermuda",
    "BT": "Bhutan",
    "BO": "Bolivia",
    "BA": "Bosnia And Herzegovina",
    "BW": "Botswana",
    "BV": "Bouvet Island",
    "BR": "Brazil",
    "IO": "British Indian Ocean Territory",
    "BN": "Brunei Darussalam",
    "BG": "Bulgaria",
    "BF": "Burkina Faso",
    "BI": "Burundi",
    "KH": "Cambodia",
    "CM": "Cameroon",
    "CA": "Canada",
    "CV": "Cape Verde",
    "KY": "Cayman Islands",
    "CF": "Central African Republic",
    "TD": "Chad",
    "CL": "Chile",
    "CN": "China",
    "CX": "Christmas Island",
    "CC": "Cocos (Keeling) Islands",
    "CO": "Colombia",
    "KM": "Comoros",
    "CG": "Congo",
    "CD": "Congo, Democratic Republic",
    "CK": "Cook Islands",
    "CR": "Costa Rica",
    "CI": "Cote D\"Ivoire",
    "HR": "Croatia",
    "CU": "Cuba",
    "CY": "Cyprus",
    "CZ": "Czech Republic",
    "DK": "Denmark",
    "DJ": "Djibouti",
    "DM": "Dominica",
    "DO": "Dominican Republic",
    "EC": "Ecuador",
    "EG": "Egypt",
    "SV": "El Salvador",
    "GQ": "Equatorial Guinea",
    "ER": "Eritrea",
    "EE": "Estonia",
    "ET": "Ethiopia",
    "FK": "Falkland Islands (Malvinas)",
    "FO": "Faroe Islands",
    "FJ": "Fiji",
    "FI": "Finland",
    "FR": "France",
    "GF": "French Guiana",
    "PF": "French Polynesia",
    "TF": "French Southern Territories",
    "GA": "Gabon",
    "GM": "Gambia",
    "GE": "Georgia",
    "DE": "Germany",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GR": "Greece",
    "GL": "Greenland",
    "GD": "Grenada",
    "GP": "Guadeloupe",
    "GU": "Guam",
    "GT": "Guatemala",
    "GG": "Guernsey",
    "GN": "Guinea",
    "GW": "Guinea-Bissau",
    "GY": "Guyana",
    "HT": "Haiti",
    "HM": "Heard Island & Mcdonald Islands",
    "VA": "Holy See (Vatican City State)",
    "HN": "Honduras",
    "HK": "Hong Kong",
    "HU": "Hungary",
    "IS": "Iceland",
    "IN": "India",
    "ID": "Indonesia",
    "IR": "Iran, Islamic Republic Of",
    "IQ": "Iraq",
    "IE": "Ireland",
    "IM": "Isle Of Man",
    "IL": "Israel",
    "IT": "Italy",
    "JM": "Jamaica",
    "JP": "Japan",
    "JE": "Jersey",
    "JO": "Jordan",
    "KZ": "Kazakhstan",
    "KE": "Kenya",
    "KI": "Kiribati",
    "KR": "Korea",
    "KW": "Kuwait",
    "KG": "Kyrgyzstan",
    "LA": "Lao People\"s Democratic Republic",
    "LV": "Latvia",
    "LB": "Lebanon",
    "LS": "Lesotho",
    "LR": "Liberia",
    "LY": "Libyan Arab Jamahiriya",
    "LI": "Liechtenstein",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "MO": "Macao",
    "MK": "Macedonia",
    "MG": "Madagascar",
    "MW": "Malawi",
    "MY": "Malaysia",
    "MV": "Maldives",
    "ML": "Mali",
    "MT": "Malta",
    "MH": "Marshall Islands",
    "MQ": "Martinique",
    "MR": "Mauritania",
    "MU": "Mauritius",
    "YT": "Mayotte",
    "MX": "Mexico",
    "FM": "Micronesia, Federated States Of",
    "MD": "Moldova",
    "MC": "Monaco",
    "MN": "Mongolia",
    "ME": "Montenegro",
    "MS": "Montserrat",
    "MA": "Morocco",
    "MZ": "Mozambique",
    "MM": "Myanmar",
    "NA": "Namibia",
    "NR": "Nauru",
    "NP": "Nepal",
    "NL": "Netherlands",
    "AN": "Netherlands Antilles",
    "NC": "New Caledonia",
    "NZ": "New Zealand",
    "NI": "Nicaragua",
    "NE": "Niger",
    "NG": "Nigeria",
    "NU": "Niue",
    "NF": "Norfolk Island",
    "MP": "Northern Mariana Islands",
    "NO": "Norway",
    "OM": "Oman",
    "PK": "Pakistan",
    "PW": "Palau",
    "PS": "Palestinian Territory, Occupied",
    "PA": "Panama",
    "PG": "Papua New Guinea",
    "PY": "Paraguay",
    "PE": "Peru",
    "PH": "Philippines",
    "PN": "Pitcairn",
    "PL": "Poland",
    "PT": "Portugal",
    "PR": "Puerto Rico",
    "QA": "Qatar",
    "RE": "Reunion",
    "RO": "Romania",
    "RU": "Russian Federation",
    "RW": "Rwanda",
    "BL": "Saint Barthelemy",
    "SH": "Saint Helena",
    "KN": "Saint Kitts And Nevis",
    "LC": "Saint Lucia",
    "MF": "Saint Martin",
    "PM": "Saint Pierre And Miquelon",
    "VC": "Saint Vincent And Grenadines",
    "WS": "Samoa",
    "SM": "San Marino",
    "ST": "Sao Tome And Principe",
    "SA": "Saudi Arabia",
    "SN": "Senegal",
    "RS": "Serbia",
    "SC": "Seychelles",
    "SL": "Sierra Leone",
    "SG": "Singapore",
    "SK": "Slovakia",
    "SI": "Slovenia",
    "SB": "Solomon Islands",
    "SO": "Somalia",
    "ZA": "South Africa",
    "GS": "South Georgia And Sandwich Isl.",
    "ES": "Spain",
    "LK": "Sri Lanka",
    "SD": "Sudan",
    "SR": "Suriname",
    "SJ": "Svalbard And Jan Mayen",
    "SZ": "Swaziland",
    "SE": "Sweden",
    "CH": "Switzerland",
    "SY": "Syrian Arab Republic",
    "TW": "Taiwan",
    "TJ": "Tajikistan",
    "TZ": "Tanzania",
    "TH": "Thailand",
    "TL": "Timor-Leste",
    "TG": "Togo",
    "TK": "Tokelau",
    "TO": "Tonga",
    "TT": "Trinidad And Tobago",
    "TN": "Tunisia",
    "TR": "Turkey",
    "TM": "Turkmenistan",
    "TC": "Turks And Caicos Islands",
    "TV": "Tuvalu",
    "UG": "Uganda",
    "UA": "Ukraine",
    "AE": "United Arab Emirates",
    "GB": "United Kingdom",
    "US": "United States",
    "UM": "United States Outlying Islands",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VU": "Vanuatu",
    "VE": "Venezuela",
    "VN": "Vietnam",
    "VG": "Virgin Islands, British",
    "VI": "Virgin Islands, U.S.",
    "WF": "Wallis And Futuna",
    "EH": "Western Sahara",
    "YE": "Yemen",
    "ZM": "Zambia",
    "ZW": "Zimbabwe"
}

ISO3_TO_ISO2_MAP = {'AFG': 'AF', 'ALA': 'AX', 'ALB': 'AL', 'DZA': 'DZ', 'ASM': 'AS', 'AND': 'AD',
                    'AGO': 'AO',
                    'AIA': 'AI', 'ATA': 'AQ', 'ATG': 'AG', 'ARG': 'AR', 'ARM': 'AM', 'ABW': 'AW',
                    'AUS': 'AU',
                    'AUT': 'AT', 'AZE': 'AZ', 'BHS': 'BS', 'BHR': 'BH', 'BGD': 'BD', 'BRB': 'BB',
                    'BLR': 'BY',
                    'BEL': 'BE', 'BLZ': 'BZ', 'BEN': 'BJ', 'BMU': 'BM', 'BTN': 'BT', 'BOL': 'BO',
                    'BIH': 'BA',
                    'BWA': "BW", 'BVT': 'BV', 'BRA': 'BR', 'IOT': 'IO', 'BRN': 'BN', 'BGR': 'BG',
                    'BFA': 'BF',
                    'BDI': 'BI', 'KHM': 'KH', 'CMR': 'CM', 'CAN': 'CA', 'CPV': 'CV', 'CYM': 'KY',
                    'CAF': 'CF',
                    'TCD': 'TD', 'CHL': 'CL', 'CHN': 'CN', 'CXR': 'CX', 'CCK': 'CC', 'COL': 'CO',
                    'COM': 'KM',
                    'COG': 'CG', 'COD': 'CD', 'COK': 'CK', 'CRI': 'CR', 'CIV': 'CI', 'HRV': 'HR',
                    'CUB': 'CU',
                    'CYP': 'CY', 'CZE': 'CZ', 'DNK': 'DK', 'DJI': 'DJ', 'DMA': 'DM', 'DOM': 'DO',
                    'ECU': 'EC',
                    'EGY': 'EG', 'SLV': 'SV', 'GNQ': 'GQ', 'ERI': 'ER', 'EST': 'EE', 'ETH': 'ET',
                    'FLK': 'FK',
                    'FRO': 'FO', 'FJI': 'FJ', 'FIN': 'FI', 'FRA': 'FR', 'GUF': 'GF', 'PYF': 'PF',
                    'ATF': 'TF',
                    'GAB': 'GA', 'GMB': 'GM', 'GEO': 'GE', 'DEU': 'DE', 'GHA': 'GH', 'GIB': 'GI',
                    'GRC': 'GR',
                    'GRL': 'GL', 'GRD': 'GD', 'GLP': 'GP', 'GUM': 'GU', 'GTM': 'GT', 'GGY': 'GG',
                    'GIN': 'GN',
                    'GNB': 'GW', 'GUY': 'GY', 'HTI': 'HT', 'HMD': 'HM', 'VAT': 'VA', 'HND': 'HN',
                    'HKG': 'HK',
                    'HUN': 'HU', 'ISL': 'IS', 'IND': 'IN', 'IDN': 'ID', 'IRN': 'IR', 'IRQ': 'IQ',
                    'IRL': 'IE',
                    'IMN': 'IM', 'ISR': 'IL', 'ITA': 'IT', 'JAM': 'JM', 'JPN': 'JP', 'JEY': 'JE',
                    'JOR': 'JO',
                    'KAZ': 'KZ', 'KEN': 'KE', 'KIR': 'KI', 'KOR': 'KR', 'KWT': 'KW', 'KGZ': 'KG',
                    'LAO': 'LA',
                    'LVA': 'LV', 'LBN': 'LB', 'LSO': 'LS', 'LBR': 'LR', 'LBY': 'LY', 'LIE': 'LI',
                    'LTU': 'LT',
                    'LUX': 'LU', 'MAC': 'MO', 'MKD': 'MK', 'MDG': 'MG', 'MWI': 'MW', 'MYS': 'MY',
                    'MDV': 'MV',
                    'MLI': 'ML', 'MLT': 'MT', 'MHL': 'MH', 'MTQ': 'MQ', 'MRT': 'MR', 'MUS': 'MU',
                    'MYT': 'YT',
                    'MEX': 'MX', 'FSM': 'FM', 'MDA': 'MD', 'MCO': 'MC', 'MNG': 'MN', 'MNE': 'ME',
                    'MSR': 'MS',
                    'MAR': 'MA', 'MOZ': 'MZ', 'MMR': 'MM', 'NAM': 'NA', 'NRU': 'NR', 'NPL': 'NP',
                    'NLD': 'NL',
                    'ANT': 'AN', 'NCL': 'NC', 'NZL': 'NZ', 'NIC': 'NI', 'NER': 'NE',
                    'NGA': 'NG', 'NIU': 'NU',
                    'NFK': 'NF', 'MNP': 'MP', 'NOR': 'NO', 'OMN': 'OM', 'PAK': 'PK', 'PLW': 'PW',
                    'PSE': 'PS',
                    'PAN': 'PA', 'PNG': 'PG', 'PRY': 'PY', 'PER': 'PE', 'PHL': 'PH', 'PCN': 'PN',
                    'POL': 'PL',
                    'PRT': 'PT', 'PRI': 'PR', 'QAT': 'QA', 'REU': 'RE', 'ROU': 'RO', 'RUS': 'RU',
                    'RWA': 'RW',
                    'BLM': 'BL', 'SHN': 'SH', 'KNA': 'KN', 'LCA': 'LC', 'MAF': 'MF', 'SPM': 'PM',
                    'VCT': 'VC',
                    'WSM': 'WS', 'SMR': 'SM', 'STP': 'ST', 'SAU': 'SA', 'SEN': 'SN', 'SRB': 'RS',
                    'SYC': 'SC',
                    'SLE': 'SL', 'SGP': 'SG', 'SVK': 'SK', 'SVN': 'SI', 'SLB': 'SB', 'SOM': 'SO',
                    'ZAF': 'ZA',
                    'SGS': 'GS', 'ESP': 'ES', 'LKA': 'LK', 'SDN': 'SD', 'SUR': 'SR', 'SJM': 'SJ',
                    'SWZ': 'SZ',
                    'SWE': 'SE', 'CHE': 'CH', 'SYR': 'SY', 'TWN': 'TW', 'TJK': 'TJ', 'TZA': 'TZ',
                    'THA': 'TH',
                    'TLS': 'TL', 'TGO': 'TG', 'TKL': 'TK', 'TON': 'TO', 'TTO': 'TT', 'TUN': 'TN',
                    'TUR': 'TR',
                    'TKM': 'TM', 'TCA': 'TC', 'TUV': 'TV', 'UGA': 'UG', 'UKR': 'UA', 'ARE': 'AE',
                    'GBR': 'GB',
                    'USA': 'US', 'UMI': 'UM', 'URY': 'UY', 'UZB': 'UZ', 'VUT': 'VU', 'VEN': 'VE',
                    'VNM': 'VN',
                    'VGB': 'VG', 'VIR': 'VI', 'WLF': 'WF', 'ESH': 'EH', 'YEM': 'YE', 'ZMB': 'ZM',
                    'ZWE': 'ZW', 'PRK': 'KP', 'SSD': 'SS', 'RKS': 'XK'}
ISO2_TO_ISO3_MAP = {'AF': 'AFG', 'AX': 'ALA', 'AL': 'ALB', 'DZ': 'DZA', 'AS': 'ASM', 'AD': 'AND',
                    'AO': 'AGO', 'AI': 'AIA', 'AQ': 'ATA', 'AG': 'ATG', 'AR': 'ARG', 'AM': 'ARM',
                    'AW': 'ABW', 'AU': 'AUS', 'AT': 'AUT', 'AZ': 'AZE', 'BS': 'BHS', 'BH': 'BHR',
                    'BD': 'BGD', 'BB': 'BRB', 'BY': 'BLR', 'BE': 'BEL', 'BZ': 'BLZ', 'BJ': 'BEN',
                    'BM': 'BMU', 'BT': 'BTN', 'BO': 'BOL', 'BA': 'BIH', 'BW': 'BWA', 'BV': 'BVT',
                    'BR': 'BRA', 'IO': 'IOT', 'BN': 'BRN', 'BG': 'BGR', 'BF': 'BFA', 'BI': 'BDI',
                    'KH': 'KHM', 'CM': 'CMR', 'CA': 'CAN', 'CV': 'CPV', 'KY': 'CYM', 'CF': 'CAF',
                    'TD': 'TCD', 'CL': 'CHL', 'CN': 'CHN', 'CX': 'CXR', 'CC': 'CCK', 'CO': 'COL',
                    'KM': 'COM', 'CG': 'COG', 'CD': 'COD', 'CK': 'COK', 'CR': 'CRI', 'CI': 'CIV',
                    'HR': 'HRV', 'CU': 'CUB', 'CY': 'CYP', 'CZ': 'CZE', 'DK': 'DNK', 'DJ': 'DJI',
                    'DM': 'DMA', 'DO': 'DOM', 'EC': 'ECU', 'EG': 'EGY', 'SV': 'SLV', 'GQ': 'GNQ',
                    'ER': 'ERI', 'EE': 'EST', 'ET': 'ETH', 'FK': 'FLK', 'FO': 'FRO', 'FJ': 'FJI',
                    'FI': 'FIN', 'FR': 'FRA', 'GF': 'GUF', 'PF': 'PYF', 'TF': 'ATF', 'GA': 'GAB',
                    'GM': 'GMB', 'GE': 'GEO', 'DE': 'DEU', 'GH': 'GHA', 'GI': 'GIB', 'GR': 'GRC',
                    'GL': 'GRL', 'GD': 'GRD', 'GP': 'GLP', 'GU': 'GUM', 'GT': 'GTM', 'GG': 'GGY',
                    'GN': 'GIN', 'GW': 'GNB', 'GY': 'GUY', 'HT': 'HTI', 'HM': 'HMD', 'VA': 'VAT',
                    'HN': 'HND', 'HK': 'HKG', 'HU': 'HUN', 'IS': 'ISL', 'IN': 'IND', 'ID': 'IDN',
                    'IR': 'IRN', 'IQ': 'IRQ', 'IE': 'IRL', 'IM': 'IMN', 'IL': 'ISR', 'IT': 'ITA',
                    'JM': 'JAM', 'JP': 'JPN', 'JE': 'JEY', 'JO': 'JOR', 'KZ': 'KAZ', 'KE': 'KEN',
                    'KI': 'KIR', 'KR': 'KOR', 'KW': 'KWT', 'KG': 'KGZ', 'LA': 'LAO', 'LV': 'LVA',
                    'LB': 'LBN', 'LS': 'LSO', 'LR': 'LBR', 'LY': 'LBY', 'LI': 'LIE', 'LT': 'LTU',
                    'LU': 'LUX', 'MO': 'MAC', 'MK': 'MKD', 'MG': 'MDG', 'MW': 'MWI', 'MY': 'MYS',
                    'MV': 'MDV', 'ML': 'MLI', 'MT': 'MLT', 'MH': 'MHL', 'MQ': 'MTQ', 'MR': 'MRT',
                    'MU': 'MUS', 'YT': 'MYT', 'MX': 'MEX', 'FM': 'FSM', 'MD': 'MDA', 'MC': 'MCO',
                    'MN': 'MNG', 'ME': 'MNE', 'MS': 'MSR', 'MA': 'MAR', 'MZ': 'MOZ', 'MM': 'MMR',
                    'NA': 'NAM', 'NR': 'NRU', 'NP': 'NPL', 'NL': 'NLD', 'AN': 'ANT', 'NC': 'NCL',
                    'NZ': 'NZL', 'NI': 'NIC', 'NE': 'NER', 'NG': 'NGA', 'NU': 'NIU', 'NF': 'NFK',
                    'MP': 'MNP', 'NO': 'NOR', 'OM': 'OMN', 'PK': 'PAK', 'PW': 'PLW', 'PS': 'PSE',
                    'PA': 'PAN', 'PG': 'PNG', 'PY': 'PRY', 'PE': 'PER', 'PH': 'PHL', 'PN': 'PCN',
                    'PL': 'POL', 'PT': 'PRT', 'PR': 'PRI', 'QA': 'QAT', 'RE': 'REU', 'RO': 'ROU',
                    'RU': 'RUS', 'RW': 'RWA', 'BL': 'BLM', 'SH': 'SHN', 'KN': 'KNA', 'LC': 'LCA',
                    'MF': 'MAF', 'PM': 'SPM', 'VC': 'VCT', 'WS': 'WSM', 'SM': 'SMR', 'ST': 'STP',
                    'SA': 'SAU', 'SN': 'SEN', 'RS': 'SRB', 'SC': 'SYC', 'SL': 'SLE', 'SG': 'SGP',
                    'SK': 'SVK', 'SI': 'SVN', 'SB': 'SLB', 'SO': 'SOM', 'ZA': 'ZAF', 'GS': 'SGS',
                    'ES': 'ESP', 'LK': 'LKA', 'SD': 'SDN', 'SR': 'SUR', 'SJ': 'SJM', 'SZ': 'SWZ',
                    'SE': 'SWE', 'CH': 'CHE', 'SY': 'SYR', 'TW': 'TWN', 'TJ': 'TJK', 'TZ': 'TZA',
                    'TH': 'THA', 'TL': 'TLS', 'TG': 'TGO', 'TK': 'TKL', 'TO': 'TON', 'TT': 'TTO',
                    'TN': 'TUN', 'TR': 'TUR', 'TM': 'TKM', 'TC': 'TCA', 'TV': 'TUV', 'UG': 'UGA',
                    'UA': 'UKR', 'AE': 'ARE', 'GB': 'GBR', 'US': 'USA', 'UM': 'UMI', 'UY': 'URY',
                    'UZ': 'UZB', 'VU': 'VUT', 'VE': 'VEN', 'VN': 'VNM', 'VG': 'VGB', 'VI': 'VIR',
                    'WF': 'WLF', 'EH': 'ESH', 'YE': 'YEM', 'ZM': 'ZMB', 'ZW': 'ZWE', 'KP': 'PRK',
                    'SS': 'SSD', 'XK': 'RKS'}


def iso3_to_iso2(country_iso3):
    """Converts iso3 to iso2 country codes

    See Also: https://www.iban.com/country-codes

    Args:
        country_iso3 : str

    Returns:
        str

    """
    return ISO3_TO_ISO2_MAP[country_iso3]


def iso2_to_iso3(country_iso2):
    """Converts iso2 to iso3 country codes

    See Also: https://www.iban.com/country-codes

    Args:
        country_iso2 : str

    Returns:
        str

    """
    return ISO2_TO_ISO3_MAP[country_iso2]


def iso2_to_name(country_iso2):
    return ISO_CODES_COUNTRY_NAME_MAP.get(country_iso2)


def fips_to_name(fips_code):
    name = FIPS_CODES_COUNTRY_NAME_MAP.get(fips_code)
    return name.split(' [')[0]
